### ISSUE TITLE
Не работает аддон в рейде Каражан Sirus x5

### ISSUE THREAD

**Issue by VladimirFunnyDevelop** [Waini4/DBM_For_Sirus#13]
Не работает аддон в рейде Каражан Sirus x5, вообще ничего не отображается, стоит намертво, может нужно как то активировать данный рейд? Папку кэша WTF удалял, переустанавливал аддон, ничего не помогает.

**Comment by Stekolnyu** [comment]
Насколько актуальная версия у тебя?
Попробуйте перед входом в каражан поставить сложность 10

**Comment by VladimirFunnyDevelop** [comment]
Версия самая последняя, сложность в аддоне выбрать или в игре?) Каражан только 10 и есть там нет режима на 25

**Comment by fxpw** [comment]
> Версия самая последняя, сложность в аддоне выбрать или в игре?) Каражан только 10 и есть, там нет режима на 25.

Каражан об или хм, и обнови версию и отпиши еще раз

**Comment by Stekolnyu** [comment]
Обновись получаеца

**Comment by VladimirFunnyDevelop** [comment]
Каражан об, пока не могу проверить, рт сегодня отменили, отпишу позже и засниму видео

**Comment by VladimirFunnyDevelop** [comment]
https://youtu.be/my5_ECUfmBM
В видео собственно ничего нет, потому что ничего не работает. РАБОТАЕТ на боссе Ловчий Аттумен.

**Comment by Stekolnyu** [comment]
Леди нет таймеров обычки, исправлю (кто-то их вырезал, осуждаю)
Было бы здорово если был стрим по фул каражану

**Comment by VladimirFunnyDevelop** [comment]
Смотритель НЕ работает, Опера - страна оз работает

**Comment by VladimirFunnyDevelop** [comment]
Дальше пока физически пройти не можем)

**Comment by Stekolnyu** [comment]
![image](https://user-images.githubusercontent.com/98555345/186431974-84a39a34-039c-4f69-9c7d-d831cabde6e3.png)
Смотритель должен работать, проверь. Опять таки обновись

**Comment by VladimirFunnyDevelop** [comment]
На деве таймеры сбитые, не правильно Покаяние отображает.

**Comment by Stekolnyu** [comment]
Нужны логи видео, нет инфы нет правок

**Comment by VladimirFunnyDevelop** [comment]
закрывайте ветку, я не смогу предоставить логи видео и инфу
