### ISSUE TITLE
Кель

### ISSUE THREAD

**Issue by Ivan-Skoryk** [Waini4/DBM_For_Sirus#2]
![image](https://user-images.githubusercontent.com/41580561/183497550-f557e319-c44d-45e1-81c5-715dac102ed3.png)

**Comment by Ivan-Skoryk** [comment]
@Waini4

**Comment by fxpw** [comment]
И след раз код присылай друже

**Comment by Ivan-Skoryk** [comment]
[C]: spellId()
   DBM-Core\DBM-Core.lua:844:
      DBM-Core\DBM-Core.lua:829
   DBM-Core\DBM-Core.lua:870:
      DBM-Core\DBM-Core.lua:864
   DBM-Core\DBM-Core.lua:933: RegisterEvents()
   DBM-TheEye\KaelThas.lua:11: in main chunk
   [C]: ?
   ..\SharedXML\FunctionOverride.lua:495: LoadAddOn()
   DBM-Core\DBM-Core.lua:3279: LoadMod()
   DBM-GUI\DBM-GUI.lua:810:
      DBM-GUI\DBM-GUI.lua:809
      
      
      
     @fxpw вот так?

**Comment by fxpw** [comment]
в пуле пофиксил
