### ISSUE TITLE
Ульдуар 10хм Метка Безликого

### ISSUE THREAD

**Issue by belozerskiy** [Waini4/DBM_For_Sirus#23]
На Генерале Везаксе не показывает на ком весит метка безликого. И не оповещает о том что повесили метку. Показывает только откат способности и то только в начале боя, флажки в опциях стоят.

**Comment by fxpw** [comment]
Какой сервер сложность рейда и надобно еще больше инфы, желательно если это х4-х5 логи

**Comment by belozerskiy** [comment]
x2, 10хм, логи постараюсь записать уже завтра, если обьяснишь как, то буду благодарен.

**Comment by belozerskiy** [comment]
Нашел в чем проблема, не указан номер спелла 312621

**Comment by belozerskiy** [comment]
> 10/13 01:13:27.715  SPELL_CAST_SUCCESS,0xF1300081F7000044,"Генерал Везакс",0x10a48,0x00000000000C902C,"Kinfu",0x512,312621,"Метка Безликого",0x20
10/13 01:13:28.464  SPELL_AURA_APPLIED,0xF1300081F7000044,"Генерал Везакс",0x10a48,0x00000000000C902C,"Kinfu",0x4000512,312621,"Метка Безликого",0x20,DEBUFF
10/13 01:13:38.478  SPELL_AURA_REMOVED,0xF1300081F7000044,"Генерал Везакс",0x10a48,0x00000000000C902C,"Kinfu",0x512,312621,"Метка Безликого",0x20,DEBUFF

**Comment by fxpw** [comment]
https://discord.gg/7cjU9xvcQY
Заходи сюда, там есть гайд в разделе с дбмом как записывать и чем
Айдишник щас залью, тему закрою, если что пиши туда либо создай еще раз тему.
