### ISSUE TITLE
Не работает dbm в око вечности, нет оповещений и таймеров.

### ISSUE THREAD

**Issue by Aragorn5534** [Waini4/DBM_For_Sirus#31]
Message: Interface\AddOns\DBM-Core\DBM-Core.lua:11115: Usage: GetAchievementLink(achievementID)
Time: 12/03/23 22:14:23
Count: 1
Stack: [C]: in function `GetAchievementLink'
Interface\AddOns\DBM-Core\DBM-Core.lua:11115: in function <Interface\AddOns\DBM-Core\DBM-Core.lua:11019>
(tail call): ?
Interface\AddOns\DBM-EyeOfEternity\Malygos.lua:45: in main chunk
[C]: ?
Interface\SharedXML\FunctionOverride.lua:269: in function `LoadAddOn'
Interface\AddOns\DBM-Core\DBM-Core.lua:3429: in function `LoadMod'
Interface\AddOns\DBM-GUI\DBM-GUI.lua:809: in function <Interface\AddOns\DBM-GUI\DBM-GUI.lua:808>

Locals: (*temporary) = "И ты не вечен"

**Comment by ButtBeware** [comment]
это не дбм, у любого аддона, который получает данные об ачиве - такая же ошибка. видимо снова накодили костылей на серваке
