### ISSUE TITLE
Пропала директория DBM-core

### ISSUE THREAD

**Issue by acolyte-py** [Waini4/DBM_For_Sirus#34]
Доброго времени суток, не знаю с чем связана проблемма, но сегодня обратил внимание что не работает дбм. Начал смотреть что пошло не так, и в итоге не долго анализа я обнаружил - что у меня просто **пропала** директория. 
Кто - то сталкивался с подобным?

**Comment by AmonRay** [comment]
проблема явно не связанная с аддоном. Перекачай

**Comment by acolyte-py** [comment]
Перекачай это понятное дело, я просто сообщил что поведение такое произошло - явно кейс не мой, я не удалял директорию)

**Comment by Waini4** [comment]
Добрый день, увы но функции само удаление папки нету ). Скорее это попытка обновления через лаунчер сируса, не уверен точно, так как не пользуюсь лаунчером а обновляюсь через апдейтер.

**Comment by acolyte-py** [comment]
Я тоже подумал об этом, потому что когда Вы сказали про обновление, я вспомнил что за не долго как я обнаружил директорию dbm-core удаленной - я обновлял аддон через лаунчер сируса, возможно это и было триггер точкой.
